### ISSUE TITLE
Swap to standard linting

### ISSUE THREAD

**Issue by hiimbex** [behaviorbot/new-issue-welcome#27]
The procedure for doing this is laid out more thoroughly here: https://github.com/behaviorbot/sentiment-bot/issues/13.

Let me know if you have any questions!

**Comment by wildan3105** [comment]
Hi, I'd like to work on this. Could you give some hint or example of the output you expect? Thanks

**Comment by hiimbex** [comment]
Hi @wildan3105, the detailed steps for how to tackle this are laid out here: https://github.com/behaviorbot/sentiment-bot/issues/13, it's a different repo, but the same steps need to be taken.

**Comment by wildan3105** [comment]
Ok. Will work on this and try to make PR at Oct 1st :smile:

**Comment by hiimbex** [comment]
Great! Let me know if anything stumps you :)

**Comment by hiimbex** [comment]
Closed via #28
