### ISSUE TITLE
.netcore3.1-angular8 project takes too long to publish

### ISSUE THREAD

**Issue by nivasceg** [behaviorbot/new-issue-welcome#52]
I'm trying to publish a .net core 3.1 - angular 8 project. The build time is less than 30 secs but it is taking 30 mins to publish. Any idea why it is taking so much time to publish?

**Comment by gr2m** [comment]
This GitHub repository is not related to .net or angular, we cannot help you here, sorry. 

Maybe try asking at https://github.com/NetCoreTemplates/angular-spa?
